# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/juju/mem_test_rw_seperate/mem_test_rw_seperate.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
# IP: The module: 'design_1_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/juju/mem_test_rw_seperate/mem_test_rw_seperate.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/juju/mem_test_rw_seperate/mem_test_rw_seperate.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
# IP: The module: 'design_1_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/juju/mem_test_rw_seperate/mem_test_rw_seperate.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
