vlib work
vlib riviera

vlib riviera/xil_defaultlib
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/smartconnect_v1_0
vlib riviera/axi_protocol_checker_v2_0_1
vlib riviera/axi_vip_v1_1_1
vlib riviera/processing_system7_vip_v1_0_3
vlib riviera/lib_pkg_v1_0_2
vlib riviera/fifo_generator_v13_2_1
vlib riviera/lib_fifo_v1_0_10
vlib riviera/lib_srl_fifo_v1_0_2
vlib riviera/lib_cdc_v1_0_2
vlib riviera/axi_datamover_v5_1_17
vlib riviera/axi_sg_v4_1_8
vlib riviera/axi_dma_v7_1_16
vlib riviera/xlconcat_v2_1_1
vlib riviera/proc_sys_reset_v5_0_12
vlib riviera/generic_baseblocks_v2_1_0
vlib riviera/axi_register_slice_v2_1_15
vlib riviera/axi_data_fifo_v2_1_14
vlib riviera/axi_crossbar_v2_1_16
vlib riviera/gigantic_mux
vlib riviera/axi_protocol_converter_v2_1_15

vmap xil_defaultlib riviera/xil_defaultlib
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_1 riviera/axi_protocol_checker_v2_0_1
vmap axi_vip_v1_1_1 riviera/axi_vip_v1_1_1
vmap processing_system7_vip_v1_0_3 riviera/processing_system7_vip_v1_0_3
vmap lib_pkg_v1_0_2 riviera/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_1 riviera/fifo_generator_v13_2_1
vmap lib_fifo_v1_0_10 riviera/lib_fifo_v1_0_10
vmap lib_srl_fifo_v1_0_2 riviera/lib_srl_fifo_v1_0_2
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap axi_datamover_v5_1_17 riviera/axi_datamover_v5_1_17
vmap axi_sg_v4_1_8 riviera/axi_sg_v4_1_8
vmap axi_dma_v7_1_16 riviera/axi_dma_v7_1_16
vmap xlconcat_v2_1_1 riviera/xlconcat_v2_1_1
vmap proc_sys_reset_v5_0_12 riviera/proc_sys_reset_v5_0_12
vmap generic_baseblocks_v2_1_0 riviera/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_15 riviera/axi_register_slice_v2_1_15
vmap axi_data_fifo_v2_1_14 riviera/axi_data_fifo_v2_1_14
vmap axi_crossbar_v2_1_16 riviera/axi_crossbar_v2_1_16
vmap gigantic_mux riviera/gigantic_mux
vmap axi_protocol_converter_v2_1_15 riviera/axi_protocol_converter_v2_1_15

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"/opt/Xilinx_tools/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/opt/Xilinx_tools/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/opt/Xilinx_tools/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"/opt/Xilinx_tools/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_1  -sv2k12 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_1  -sv2k12 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_3  -sv2k12 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_1 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_10 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_17 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_8 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/5f94/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_16 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/bf8c/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_dma_0_0/sim/design_1_axi_dma_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/e030/hdl/verilog/pseudo_random.v" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/e030/hdl/verilog/mem_write_hw_CONTROL_BUS_s_axi.v" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/e030/hdl/verilog/mem_write.v" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/e030/hdl/verilog/mem_write_hw.v" \
"../../../bd/design_1/ip/design_1_mem_write_hw_0_0/sim/design_1_mem_write_hw_0_0.v" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/0b9b/hdl/verilog/mem_read_hw.v" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/0b9b/hdl/verilog/mem_read_hw_CONTROL_BUS_s_axi.v" \
"../../../bd/design_1/ip/design_1_mem_read_hw_0_0/sim/design_1_mem_read_hw_0_0.v" \

vlog -work xlconcat_v2_1_1  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_15  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_14  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_16  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xbar_2/sim/design_1_xbar_2.v" \
"../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
"../../../bd/design_1/sim/design_1.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.v" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0_gigantic_mux.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/sim/bd_f60c_g_inst_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_2/sim/bd_f60c_slot_1_aw_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_3/sim/bd_f60c_slot_1_w_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_4/sim/bd_f60c_slot_1_b_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_5/sim/bd_f60c_slot_1_ar_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_6/sim/bd_f60c_slot_1_r_0.v" \
"../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.v" \

vlog -work axi_protocol_converter_v2_1_15  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6180/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/a08d/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/6851/hdl/verilog" "+incdir+../../../../mem_test_rw_seperate.srcs/sources_1/bd/design_1/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx_tools/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
"../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
"../../../bd/design_1/ip/design_1_s01_data_fifo_0/sim/design_1_s01_data_fifo_0.v" \
"../../../bd/design_1/ip/design_1_s00_data_fifo_0/sim/design_1_s00_data_fifo_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

