// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMEM_WRITE_HW_H
#define XMEM_WRITE_HW_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmem_write_hw_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XMem_write_hw_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XMem_write_hw;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMem_write_hw_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMem_write_hw_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMem_write_hw_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMem_write_hw_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMem_write_hw_Initialize(XMem_write_hw *InstancePtr, u16 DeviceId);
XMem_write_hw_Config* XMem_write_hw_LookupConfig(u16 DeviceId);
int XMem_write_hw_CfgInitialize(XMem_write_hw *InstancePtr, XMem_write_hw_Config *ConfigPtr);
#else
int XMem_write_hw_Initialize(XMem_write_hw *InstancePtr, const char* InstanceName);
int XMem_write_hw_Release(XMem_write_hw *InstancePtr);
#endif

void XMem_write_hw_Start(XMem_write_hw *InstancePtr);
u32 XMem_write_hw_IsDone(XMem_write_hw *InstancePtr);
u32 XMem_write_hw_IsIdle(XMem_write_hw *InstancePtr);
u32 XMem_write_hw_IsReady(XMem_write_hw *InstancePtr);
void XMem_write_hw_EnableAutoRestart(XMem_write_hw *InstancePtr);
void XMem_write_hw_DisableAutoRestart(XMem_write_hw *InstancePtr);

void XMem_write_hw_Set_activity(XMem_write_hw *InstancePtr, u32 Data);
u32 XMem_write_hw_Get_activity(XMem_write_hw *InstancePtr);
void XMem_write_hw_Set_mask(XMem_write_hw *InstancePtr, u64 Data);
u64 XMem_write_hw_Get_mask(XMem_write_hw *InstancePtr);

void XMem_write_hw_InterruptGlobalEnable(XMem_write_hw *InstancePtr);
void XMem_write_hw_InterruptGlobalDisable(XMem_write_hw *InstancePtr);
void XMem_write_hw_InterruptEnable(XMem_write_hw *InstancePtr, u32 Mask);
void XMem_write_hw_InterruptDisable(XMem_write_hw *InstancePtr, u32 Mask);
void XMem_write_hw_InterruptClear(XMem_write_hw *InstancePtr, u32 Mask);
u32 XMem_write_hw_InterruptGetEnabled(XMem_write_hw *InstancePtr);
u32 XMem_write_hw_InterruptGetStatus(XMem_write_hw *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
