// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmem_read_hw.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMem_read_hw_CfgInitialize(XMem_read_hw *InstancePtr, XMem_read_hw_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMem_read_hw_Start(XMem_read_hw *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMem_read_hw_IsDone(XMem_read_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMem_read_hw_IsIdle(XMem_read_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMem_read_hw_IsReady(XMem_read_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMem_read_hw_EnableAutoRestart(XMem_read_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMem_read_hw_DisableAutoRestart(XMem_read_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XMem_read_hw_InterruptGlobalEnable(XMem_read_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_GIE, 1);
}

void XMem_read_hw_InterruptGlobalDisable(XMem_read_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_GIE, 0);
}

void XMem_read_hw_InterruptEnable(XMem_read_hw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_IER);
    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XMem_read_hw_InterruptDisable(XMem_read_hw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_IER);
    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XMem_read_hw_InterruptClear(XMem_read_hw *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMem_read_hw_WriteReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XMem_read_hw_InterruptGetEnabled(XMem_read_hw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_IER);
}

u32 XMem_read_hw_InterruptGetStatus(XMem_read_hw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMem_read_hw_ReadReg(InstancePtr->Control_bus_BaseAddress, XMEM_READ_HW_CONTROL_BUS_ADDR_ISR);
}

